
export enum Genres {
    "_1"="Action",
    "_39"="Action & Adventure",
    "_30"="Adult",
    "_2"="Adventure",
    "_3"="Animation",
    "_33"="Anime",
    "_31"="Biography",
    "_4"="Comedy",
    "_5"="Crime",
    "_6"="Documentary",
    "_7"="Drama",
    "_8"="Family",
    "_9"="Fantasy",
    "_34"="Food",
    "_28"="Game Show",
    "_10"="History",
    "_11"="Horror",
    "_21"="Kids",
    "_12"="Music",
    "_32"="Musical",
    "_13"="Mystery",
    "_36"="Nature",
    "_22"="News",
    "_23"="Reality",
    "_14"="Romance",
    "_40"="Sci-Fi & Fantasy",
    "_15"="Science Fiction",
    "_25"="Soap",
    "_29"="Sports",
    "_37"="Supernatural",
    "_26"="Talk",
    "_17"="Thriller",
    "_35"="Travel",
    "_38"="TV Movie",
    "_18"="War",
    "_41"="War & Politics",
    "_19"="Western"
}

export enum Services {
    "_203" = "Netflix", 
    "_157" = "Hulu",
    "_26" = "Amazon",
    "_387" = "HBO MAX",
    "_372" = "Disney +",
    "_371" = "AppleTV+",
    "_444" = "Paramount+",
    "_389" = "Peacock Premium",
    "_307" = "VUDU"
}